Bently Luxury Cars
cvalencia1991/Budget-app pull request #1
Opened 2023-02-16 13:15 UTC by cvalencia1991

2023-02-16 16:05 UTC, 1GORDON requested changes
##
## Hi @cvalencia1991 ✋

Good job so far!

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [ ] Great job presenting the project features in your video presentation. However, as suggested in the project requirements, you forgot to showcase the piece of code you are proud of writing. Kindly highlight a piece of the code you find interesting or proud of making.

_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 16:05 UTC, 1GORDON commented on app/views/layouts/application.html.erb
> +<!DOCTYPE html>
Great job @cvalencia1991 🤝

- [ ] Great job on implementing the functionality. However, I would suggest you stick to the design guidelines as much as possible.
- Given design
![given-design](https://user-images.githubusercontent.com/63917725/219420568-95aec41b-f9bc-4dae-8be1-e6d9fd3e7d90.PNG)
- Your design
![your-design](https://user-images.githubusercontent.com/63917725/219420655-eb825f96-c780-4988-9227-7b3bff6d0631.PNG)

2023-02-16 16:07 UTC, cvalencia1991 commented on app/views/layouts/application.html.erb
> +<!DOCTYPE html>
but the requirements is working well ??

2023-02-16 23:21 UTC, brytebee approved these changes
Hello, @cvalencia1991👋 ,

------

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great UI design.✔️
- App functions as it should.✔️

------

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

<img src="https://media0.giphy.com/media/ytTYwIlbD1FBu/giphy.gif"/>

Good luck! 🎉 

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 00:29 UTC, cvalencia1991 commented
thank you 👍

2023-02-17 00:29 UTC, merged